### ISSUE TITLE
installation path

### ISSUE THREAD

**Issue by chrisdane** [pgierz/esm-viz#16]
I would like to set the installation path to change it from the default `~/.local/`. Is this possible?
This would also kind of solve the issue that the user needs to add the installation manually to `PATH`, which is maybe not the best procedere?

Thanks!

**Comment by pgierz** [comment]
See the `pip` manual:
https://pip.pypa.io/en/stable/reference/pip_install/#cmdoption-prefix

**Comment by chrisdane** [comment]
Paul ^^ This answer is not user friendly :D
If you know the answer, please write here; plus considering putting it into the readme.

**Comment by pgierz** [comment]
....fine. The following will be added to the readme:

If you are root, everything should work out of the box. Otherwise, pass the `--user` prefix to `pip`. This will install the package under `${HOME}/.local/`, where binaries are in the `bin` folder, and Python code in `lib`. You can override this directory with the `--prefix` flag.

**Comment by chrisdane** [comment]
I would be happy to see a complete installation-with-prefix command in the readme. At the moment, I need to construct it by myself. This is still not user friendly >_<
